WEB2021Apr_P03_T4/Controllers/AdminJudgeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P03_T4.Models;
using WEB2021Apr_P03_T4.DAL;

namespace WEB2021Apr_P03_T4.Controllers
{
    public class AdminJudgeController : Controller
    {
        private AdminCompJudgeDal compjudgeDAL = new AdminCompJudgeDal();

        public ActionResult Remove(int compID, int judgeID)
        {

            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (compID == null || judgeID == null )
            {
                return RedirectToAction("Index", "Home");
            }

            compjudgeDAL.Delete(compID, judgeID);
            return RedirectToAction("CompJudgeDashboard", "Administrator");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Assign(CompetitionJudge compJudge)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            compjudgeDAL.Add(compJudge);
            return RedirectToAction("CompJudgeDashboard", "Administrator");
        }

        public ActionResult AssignDouble(CompetitionDoubleJudge cdj)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (cdj.JudgeID_first == cdj.JudgeID_second) {
                   TempData["doubleJudgeError"] = "Please Enter Two Unique Judges!";
                return RedirectToAction("CompJudgeAssignDouble", "Administrator");
            }
            compjudgeDAL.AddDouble(cdj);
            return RedirectToAction("CompJudgeDashboard", "Administrator");
        }
    }
}

WEB2021Apr_P03_T4/Controllers/AdministratorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P03_T4.Models;
using WEB2021Apr_P03_T4.DAL;

namespace WEB2021Apr_P03_T4.Controllers
{
    //  ̿̿ ̿̿ ̿̿ ̿'̿'\̵͇̿̿\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿     hasta la vista fuck asp

    public class AdministratorController : Controller
    {
        private AreaOfInterestDAL aoiDal = new AreaOfInterestDAL();
        private CompetitionDAL compDal = new CompetitionDAL();
        private AdminCompetitionDAL adminCompDal = new AdminCompetitionDAL();
        private AdminCompJudgeDal judgeAdminDAL = new AdminCompJudgeDal();

        public IActionResult Index()
        {
            return View();
        }


        //  AREAINTEREST REDIRECTION
        public IActionResult AreaInterestDashboard()
        {
            // Stop accessing the action if not logged in or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<AreaInterestViewModel> AreaInterestVMList = aoiDal.GetAreaInterestVMList();
            return View(AreaInterestVMList);
        }
        public ActionResult AreaInterestCreate()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public ActionResult AreaInterestDelete(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null) {
                return RedirectToAction("AreaInterestDashboard", "Administrator");
            }
            Models.AreaInterest aoi = aoiDal.GetDetails(id);
            if (aoi == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("AreaInterestDashboard", "Administrator");
            }
            return View(aoi);
        }


        //  COMPETITION REDIRECTION
        public IActionResult CompetitionDashboard()
        {
            // Stop accessing the action if not logged in or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<Competition> competitionList = compDal.GetCompetition();
            return View(competitionList);
        }

        public ActionResult CompetitionCreate(Competition competition) {
            ViewData["AreaInterestVM"] = aoiDal.GetAreaInterestVMList();
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View(competition);
        }

        public ActionResult CompetitionDelete(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return RedirectToAction("CompetitionDashboard", "Administrator");
            }
            Competition comp = adminCompDal.GetDetails((int)id);
            if (comp == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("CompetitionDashboard", "Administrator");
            }
            return View(comp);
        }
        public IActionResult CompJudgeDashboard()
        {
            // Stop accessing the action if not logged in or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<CompetitionJudgeViewModel> compjudgeListVM = judgeAdminDAL.GetCompetitionJudgeViewModel();
            return View(compjudgeListVM);
        }

        public ActionResult CompJudgeAssign(int? compID)
        {
            ViewData["judgelist"] = judgeAdminDAL.GetJudgeList();
            //ViewData["complist"] = judgeAdminDAL.GetCompetitionJudge_Alternating_List(2);
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["CompID"] = compID;
            return View();
        }

        public ActionResult CompJudgeAssignDouble()
        {
            ViewData["judgelist"] = judgeAdminDAL.GetJudgeList();
            ViewData["complist"] = judgeAdminDAL.GetCompetitionJudge_Alternating_List(1);
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult CompJudgeDelete()
        {
            ViewData["judgelist"] = judgeAdminDAL.GetJudgeList();
            ViewData["complist"] = judgeAdminDAL.getCompetitionList();
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

    }
}

WEB2021Apr_P03_T4/Views/Administrator/AreaInterestCreate.cshtml
@model WEB2021Apr_P03_T4.Models.AreaInterest

@{
    ViewData["Title"] = "Area of Interest | Create";
}

<h1 style="margin-top:100px;margin-bottom:100px; text-align:center;" >AreaInterestCreate</h1>

<hr />
<div class="row">
    <div style="background-color:rgb(255 255 255 / 0.10);padding:40px;margin-bottom:200px" class="container-fluid">
        <form asp-action="AreaInterestCreate" asp-controller="AreaInterest">
            <div class="row">
                @*<div class="col col-4">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="AreaInterestID" class="control-label"></label>
                        <input asp-for="AreaInterestID" class="form-control" disabled />
                        <span asp-validation-for="AreaInterestID" class="text-danger"></span>
                    </div>
                </div>*@
                <div class="col col-12">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <input type="submit" value="Create New Area of Interest" class="btn btn-success container-fluid" style="border-radius:0px;height:100px;margin:15px" />
            </div>
        </form>
        <div>
            <a class="text-center container-fluid" asp-action="AreaInterestDashboard">Back to List</a>
        </div>
    </div>
</div>

WEB2021Apr_P03_T4/Views/Administrator/AreaInterestDashboard.cshtml
@model IEnumerable<WEB2021Apr_P03_T4.Models.AreaInterestViewModel>

@{
    ViewData["Title"] = "Area of Interest | Dashboard";
}

<h1 style="margin-top:100px;text-align:center;">Area Of Interest Dashboard</h1>
<p style="margin-top:25px;margin-bottom:100px; text-align:center;" class="text-secondary">View & Modify All Area of Interest</p>

<div style="background-color:rgb(255 255 255 / 0.10);padding:40px;">
    <table class="table table-borderless text-white container-fluid table-striped">
        <thead style="border-bottom: solid 1px white;">
            <tr>
                <th>ID</th>
                <th>Area of Interest (@Model.ToList().Count().ToString())</th>
                <th class="text-center">Competitions</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @*<tr>
                    <td colspan="4"><hr style="border-top:1.5px solid lightgrey;"></td>
                </tr>*@
            <tr>
                <!-- STUFF GOES HERE -->
                @if (Model.ToList().Count > 0)
                {
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.AreaInterestID.ToString()</td>
                        <td>@item.Name</td>
                        <td class="text-center">@item.CompetitionCount.ToString()</td>
                        @if (item.CompetitionCount < 1)
                        {
                            <td class="text-center">
                                <a class="text-danger" class="btn" style="margin-right:10px;" method="post"
                                   asp-action="AreaInterestDelete"
                                   asp-controller="Administrator"
                                   asp-route-id="@item.AreaInterestID">Remove</a>
                            </td>
                        }
                        else
                        {
                            @*<td class="text-center text-primary"><a href="#">View This Competition</a></td>*@
                            <td></td>
                        }
                        <td class="text-center">
                        </td>
                    </tr>
                }
                }
                else
                {
                <td colspan="4"><span style="color:red">No record found!</span></td>
            }
                </tr>
                </tbody>
            </table>
            <!-- Table Controls -->
        </div>
        <div class="bg-secondary" style="margin-bottom: 100px; padding:20px;">
            <button onclick="location.href='@Url.Action("AreaInterestCreate","Administrator")'" style="border-radius:0px;height:100px" type="button" class="btn btn-success text-white container-fluid">Create New Area of Interest</button>
        </div>

WEB2021Apr_P03_T4/Views/Administrator/AreaInterestDelete.cshtml
@model WEB2021Apr_P03_T4.Models.AreaInterest

@{
    ViewData["Title"] = "Area of Interest | Delete";
}

<h1 style="margin-top:100px;margin-bottom:100px; text-align:center;" >Area of Interest Delete Confirmation</h1>

<div style="background-color:rgb(255 255 255 / 0.10);padding:40px;" style="margin-bottom:250px;">
    <h4>Are you sure you want to delete this?</h4>
    <hr />
        <div class="form-group row">
            <label asp-for="AreaInterestID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="AreaInterestID" readonly class="form-control-plaintext text-warning"/>
            </div>
        </div>
        <div class="form-group row" style="margin-bottom:50px">
            <label asp-for="Name"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Name" readonly class="form-control-plaintext text-warning" />
            </div>
        </div >
    @*<dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AreaInterestID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AreaInterestID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>*@

<a asp-controller="AreaInterest" asp-action="Delete" asp-route-id="@Model.AreaInterestID" style="border-radius:0px;padding:25px" type="button" class="btn btn-danger text-white container-fluid btn">Delete This Area of Interest</a>

        <div style="margin-top:50px;margin-bottom:50px;">
            <a class="text-center container-fluid" asp-action="AreaInterestDashboard">Back to List</a>
        </div>
</div>

WEB2021Apr_P03_T4/Views/Administrator/CompJudgeAssign.cshtml
@model WEB2021Apr_P03_T4.Models.CompetitionJudge

@{
    ViewData["Title"] = "CompJudgeAssign";
}

<h1 style="margin-top:100px; text-align:center;">Assign Judge To Competition</h1>
<p style="margin-top:25px;margin-bottom:100px; text-align:center;" class="text-secondary">Assign More Judges To Competition</p>
    <div style="background-color:rgb(255 255 255 / 0.10);padding:40px; margin-bottom:200px;" class="row">
            <div class="mx-auto col-6">
                <form asp-controller="AdminJudge" asp-action="Assign">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="form-group col-6">
                            <label asp-for="JudgeID" class="control-label">Judge Name</label>
                            <br />
                            <select style="padding:20px"
                                    class="form-select" asp-for="JudgeID"
                                asp-items="@(new SelectList(ViewData["judgelist"] as List <Judge>, "JudgeID", "JudgeName"))"></select>
                            <br /><span asp-validation-for="JudgeID" class="text-danger"></span>
                        </div>
                        <div class="form-group col-6">
                            @*<label asp-for="CompetitionID" class="control-label">Competition Name</label>
                            <br />
                            <select style="padding:20px"
                                    class="form-select" asp-for="CompetitionID"
                                    asp-items="@(new SelectList(ViewData["complist"] as List <CompetitionJudgeViewModel>, "CompetitionID", "CompetitionName"))"></select>
                            <br /><span asp-validation-for="CompetitionID" class="text-danger"></span>*@

                            <label asp-for="CompetitionID"
                                   class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9 col-md-5">
                                <input asp-for="CompetitionID" readonly class="form-control-plaintext text-warning" value="@ViewData["compID"]" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add Judge" class="btn btn-success container-fluid" style="padding:25px;border-radius:0px;" />
                    </div>
                    <div>
                        <a asp-controller="Administrator" asp-action="CompJudgeDashboard">Back to List</a>
                    </div>
                </form>
            </div>
        </div>

WEB2021Apr_P03_T4/Views/Administrator/CompJudgeAssignDouble.cshtml
@model WEB2021Apr_P03_T4.Models.CompetitionDoubleJudge

@{
    ViewData["Title"] = "CompJudgeAssign";
}

<h1 style="margin-top:100px;margin-bottom:25px; text-align:center;">Assign Judge To Competition</h1>
<p style="margin-bottom:100px; text-align:center;" class="text-secondary">Assign a minimum of two Judges to a Competition without any</p>

<hr />
<div class="row" style="margin-bottom:200px">
    <div class="mx-auto" style="background-color:rgb(255 255 255 / 0.10);padding:40px;">
        <form asp-controller="AdminJudge" asp-action="AssignDouble">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompetitionID" class="control-label">Competition Name</label>
                <br />
                <select style="padding:20px"
                        class="form-select" asp-for="CompetitionID"
                        asp-items="@(new SelectList(ViewData["complist"] as List <CompetitionJudgeViewModel>, "CompetitionID", "CompetitionName"))"></select>
                <br /><span asp-validation-for="CompetitionID" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-6">
                    <label asp-for="JudgeID_first" class="control-label">Judge 1</label>
                    <br />
                    <select style="padding:20px"
                            class="form-select" asp-for="JudgeID_first"
                            asp-items="@(new SelectList(ViewData["judgelist"] as List <Judge>, "JudgeID", "JudgeName"))"></select>
                    <br /><span asp-validation-for="JudgeID_first" class="text-danger"></span>
                </div>
                <div class="form-group col-6">
                    <label asp-for="JudgeID_second" class="control-label">Judge 2</label>
                    <br />
                    <select style="padding:20px"
                            class="form-select" asp-for="JudgeID_second"
                            asp-items="@(new SelectList(ViewData["judgelist"] as List <Judge>, "JudgeID", "JudgeName"))"></select>
                    <br /><span asp-validation-for="JudgeID_second" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <br><span style="margin-top:25px; margin-bottom:25px; color:red;">@TempData["doubleJudgeError"]</span><br>
                <input type="submit" value="Assign New Judges" class="btn btn-success container-fluid" style="padding:25px;border-radius:0px;" />
            </div>
            <div>
                <a class="text-center" asp-controller="Administrator" asp-action="CompJudgeDashboard">Back to List</a>
            </div>
        </form>
    </div>
</div>

WEB2021Apr_P03_T4/Views/Administrator/CompJudgeDashboard.cshtml
@model IEnumerable<WEB2021Apr_P03_T4.Models.CompetitionJudgeViewModel>

@{
    ViewData["Title"] = "Competition Judge | Dashboard";
}

<h1 style="margin-top:100px; text-align:center;">Competition Judge Dashboard</h1>
<p style="margin-top:25px;margin-bottom:100px; text-align:center;" class="text-secondary">View & Modify All Competitions and Judges</p>
<div style="background-color:rgb(255 255 255 / 0.10);padding:40px;">
    <h3 style="margin-bottom:20px; text-align:center;">Assigned Judges</h3>

    <table class="table table-borderless text-white table-striped">
        <thead style="border-bottom: solid 1px white;">
            <tr>
                <th>Judge ID</th>
                <th>Judge Name</th>
                <th>Competition Name</th>
                <th>Area Interest Name</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr style="padding-top:10px;padding-bottom:10px;">
                <!-- STUFF GOES HERE -->
                @if (Model.ToList().Count > 0)
                {
                    @foreach (var item in Model)
                    {
            <tr>
                <td>@item.JudgeID</td>
                <td>@item.JudgeName</td>
                @*<td>@item.CompetitionID</td>*@
                <td>@item.CompetitionName</td>
                <td>@item.AreaInterestName</td>
                @if (item.JudgeID != 0)
                {
                    <td class="text-center text-success">
                        <a class="text-primary" class="btn" method="post"
                           asp-action="CompJudgeAssign"
                           asp-controller="Administrator"
                           asp-route-compID="@item.CompetitionID">
                            Add
                        </a>
                    </td>
                    <td class="text-center text-success">
                        <a class="text-danger" class="btn" method="post"
                           asp-action="Remove"
                           asp-controller="AdminJudge"
                           asp-route-judgeID="@item.JudgeID"
                           asp-route-compID="@item.CompetitionID">
                            Remove
                        </a>
                    </td>
                }
                else
                {
                }
                <td class="text-center">
                </td>
            </tr>
                }
                }
                else
                {
                <td colspan="5"><span style="color:red">No record found!</span></td>
            }
                </tr>

                </tbody>
            </table>
            <!-- Table Controls -->
        </div>
        <div class="bg-secondary" style="margin-bottom: 100px; padding:20px;">
            <button onclick="location.href='@Url.Action("CompJudgeAssignDouble","Administrator")'" style="border-radius:0px;height:100px" type="button" class="btn btn-success text-white container-fluid">Assign a Judge To A New Competition</button>
        </div>

WEB2021Apr_P03_T4/Views/Administrator/CompJudgeDelete.cshtml
@model WEB2021Apr_P03_T4.Models.CompetitionJudge

@{
    ViewData["Title"] = "CompJudgeDelete";
}

<h1>CompJudgeDelete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompetitionJudge</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompetitionID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompetitionID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JudgeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JudgeID)
        </dd>
    </dl>z
    
    <form asp-action="CompJudgeDelete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WEB2021Apr_P03_T4/Views/Administrator/CompetitionCreate.cshtml
@model WEB2021Apr_P03_T4.Models.Competition

@{
    ViewData["Title"] = "CreateCompetition";
}

<h1 style="margin-top:100px;margin-bottom:100px; text-align:center;">Create Competition</h1>

<hr />
<div class="row" style="margin-bottom:200px">
    <div class="mx-auto col-6">
        <form asp-action="SubmitCreateCompetition" asp-controller="Competition">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AreaInterestID" class="control-label"></label>
                <br />
                <select class="form-select" asp-for="AreaInterestID"
                        asp-items="@(new SelectList(ViewData["AreaInterestVM"] as List <AreaInterestViewModel>, "AreaInterestID", "Name"))"></select>
                <br /><span asp-validation-for="AreaInterestID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompetitionName" class="control-label"></label>
                <input asp-for="CompetitionName" required class="form-control" />
                <span asp-validation-for="CompetitionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ResultReleasedDate" class="control-label"></label>
                <input asp-for="ResultReleasedDate" class="form-control" />
            </div>
            <br><span style="margin-top:25px; margin-bottom:25px; color:red;">@TempData["EndDateWrong"]@TempData["ResRelWrong"]</span><br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div>
                <a asp-controller="Administrator" asp-action="CompetitionDashboard">Back to List</a>
            </div>

        </form>
    </div>
</div>

WEB2021Apr_P03_T4/Views/Administrator/CompetitionDashboard.cshtml
@model IEnumerable<WEB2021Apr_P03_T4.Models.Competition>

@{
    ViewData["Title"] = "Comeptition | Dashboard";
}

<h1 style="margin-top:100px;text-align:center;">Competition Dashboard</h1>
<p style="margin-top:25px;margin-bottom:100px; text-align:center;" class="text-secondary">View & Modify All Competitions</p>
<div style="background-color:rgb(255 255 255 / 0.10);padding:40px;">
    <table class="table table-borderless text-white table-striped">
        <thead style="border-bottom: solid 1px white;">
            <tr>
                <th>ID</th>
                <th>Area of Interest ID</th>
                <th class="text-center">Competition Name</th>
                <th class="text-center">Start Date</th>
                <th class="text-center">End Date</th>
                <th class="text-center">Result Release Date</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @*<tr>
                    <td colspan="4"><hr style="border-top:1.5px solid lightgrey;"></td>
                </tr>*@
            <tr>
                <!-- STUFF GOES HERE -->
                @if (Model.ToList().Count > 0)
                {
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.CompetitionID.ToString()</td>
                        <td>@item.AreaInterestID.ToString()</td>
                        <td>@item.CompetitionName.ToString()</td>
                        <td>@item.StartDate.ToString()</td>
                        <td>@item.EndDate.ToString()</td>
                        <td>@item.ResultReleasedDate.ToString()</td>

                        <td class="text-center">
                            <a class="text-danger" class="btn" method="post"
                               asp-action="CompetitionDelete"
                               asp-controller="Administrator"
                               asp-route-id="@item.CompetitionID">Remove</a>
                        </td>
                    </tr>
                }
                }
                else
                {
                <td colspan="4"><span style="color:red">No record found!</span></td>
            }
                </tr>
                </tbody>
            </table>
            <!-- Table Controls -->
        </div>
        <div class="bg-secondary" style="margin-bottom: 100px; padding:20px;">
            <button onclick="location.href='@Url.Action("CompetitionCreate","Administrator")'" style="border-radius:0px;height:100px" type="button" class="btn btn-success text-white container-fluid">Create New Competition</button>
        </div>